name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: yahavi/setup-jfrog-cli@update-cli
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
          JFROG_CLI_BUILD_NAME: $JFROG_CLI_BUILD_NAME
          JFROG_CLI_BUILD_NUMBER: $JFROG_CLI_BUILD_NUMBER
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'    
      - name: Run JFrog CLI
        run: |
          env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
          export CI=true 
          jfrog rt mvnc --server-id-deploy aol --repo-deploy-releases libs-release-local --repo-deploy-snapshots libs-snapshot-local
          jfrog rt mvn clean install -f pom.xml    
          # Collect environment variables for the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp
          #Scan the build
          jfrog rt bs
