name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: yahavi/setup-jfrog-cli@update-cli
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
          JFROG_CLI_BUILD_NAME: $JFROG_CLI_BUILD_NAME
          JFROG_CLI_BUILD_NUMBER: $JFROG_CLI_BUILD_NUMBER
      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp
          #Scan the build
          jfrog rt bs
