name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with: 
          version: 1.46.1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jfrog rt bce AKS-Deployment ${{ github.run_number }}
          # Publish build info
          jfrog rt bp AKS-Deployment ${{ github.run_number }}
